# Generated by Django 5.0.3 on 2024-11-02 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userattendance',
            name='break_end_time',
        ),
        migrations.RemoveField(
            model_name='userattendance',
            name='break_start_time',
        ),
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('break_start_time', models.DateTimeField(blank=True, null=True)),
                ('break_end_time', models.DateTimeField(blank=True, null=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='employee.userattendance')),
            ],
        ),
    ]
